### ISSUE TITLE
Unstashing changes deletes stash, plus 2 other things

### ISSUE THREAD

**Issue by BlakeTrebelhorn** [GitFiend/Support#11]
I'm not sure if this is supposed to happen, but i lost some of my stashes when I unstashed them. It'd be nice to have an option to keep them (and also name stashed when stashing).

I think it'd would also be nice to turn off auto-fetch on focus. There's been a few times where I've tried to commit something, but it can't write because there's a lock on the git file because it's fetching.

Finally, it would be really nice to see recently used git messages like I can in Eclipse by hitting <kbd>ctrl</kbd> + <kbd>space</kbd>

**Comment by GitFiend** [comment]
Thanks BlakeTrebelhorn. These are good suggestions. The deleting of stashes when unstashing is intended, but probably a bad default.

**Comment by BlakeTrebelhorn** [comment]
@GitFiend I just updated to v0.20 Thanks for implementing my requests, I really appreciate it.

**Comment by aaaidan** [comment]
Hi Toby!

Firstly, well done on the implementation of stashes so far. It's *really* wonderful to be able to create them in a granular way. I also love that they stick around at the top with the rest of the changesets, which (now that I see it) is so obviously where they belong!

Second, regarding autodelete, I actually prefer the original behaviour. I _always_ want to delete my stashes when they are (successfully) applied because, almost by definition, they have served their purpose. Having stashes stick around after being applied can lead to a confusing proliferation of stale stashes! For me (at least) the old behaviour was more sensible.

I don't want to advocate for a user preference or dialog needlessly, and if I squint, I can imagine scenarios where you'd want to apply a stash to multiple branches. I'd really like to hear more about why @BlakeTrebelhorn prefers to keep stashes around, and any thoughts you have @GitFiend

**Comment by GitFiend** [comment]
Hi Aiden! Thanks for the comments, I really appreciate it.

I usually want to delete my stashes after I unstash: It seems cleaner, and it won't delete if there's a conflict. Recently, however, I've been putting temporary debug code in a stash. It's easier to throw it away, and take it out again later than re-stash. I would also be interested in hearing other people's reasons for keeping them.

Git has terms for both cases:
apply - unstash and keep
pop - unstash and discard

I think I will consider having both.

**Comment by BlakeTrebelhorn** [comment]
Yep, that's exactly the reason I apply some of my stashes instead of popping them. I have debug code that I need to flip flop back and forth between that should never move forward towards master, but is very useful for programming locally. I do get the need to have both, and I think popping makes sense most of the time.
