### ISSUE TITLE
Multiple selection and bulk operations

### ISSUE THREAD

**Issue by oztrkemree** [GitFiend/Support#156]
Hello there! We have been using GitFriend as a team for a while now and we really appreciate its simplicity and ease of use. Thank you for that.

We work on various projects and often make many changes to them. We have realized that selecting multiple file and discarding them together is crucial for us. Is it possible to add this feature? Thank you in advance.

**Comment by GitFiend** [comment]
Hi @oztrkemree, thanks for the feedback.

I've made some improvements that will be available soon:
 - The discard all button is now like the stash button. There's an option for discard all or discard selected
 - You can double click a changed file to toggle it's selection
 
In the future, I'm also planning on improving how the files are listed so that it would be easy to say select/deselect all the files in folder.
