### ISSUE TITLE
Can't read changes over 2000 changed files

### ISSUE THREAD

**Issue by yama24** [GitFiend/Support#163]
when i see in the github desktop i can find changes

![image](https://github.com/GitFiend/Support/assets/33719224/be3acd41-5665-4949-9e71-e1cf7915ec93)

but when i open GitFiend, i can't click  Changes button
![image](https://github.com/GitFiend/Support/assets/33719224/6026ab94-7e93-45fb-adf8-3460034f2f3f)

this problem only in my Ubuntu PC, in my Windows PC work normally.

**Comment by GitFiend** [comment]
I just tried this with 15000 files on ubuntu and wasn't able to reproduce the issue. There may be something about your repo confusing gitfiend? You could try opening the dev tools and seeing if there are any errors? (View -> Toggle Devloper Tools). Do you have a recent version of ubuntu and git installed?

**Comment by yama24** [comment]
i use Ubuntu 22.04 jammy and git version 2.34.1

**Comment by yama24** [comment]
i can't find any error,, 
![image](https://github.com/GitFiend/Support/assets/33719224/8269a758-9c4c-4884-9c84-5e7a5735a701)

and load_wip_patches return null
![image](https://github.com/GitFiend/Support/assets/33719224/55c56040-4e7a-48ab-abae-b367d472ce88)

**Comment by GitFiend** [comment]
Thanks for the investigation, that's helpful. It looks like a parser is failing.

I'm running this command: `git status --porcelain -uall -z`, and then parsing the result and it looks like that's failing due to an unhandled case. (load_wip_patches in https://github.com/GitFiend/rust-server/blob/main/src/git/queries/wip/wip_patches.rs in case you are interested)

I can read through the git documentation to see if there's a case I've missed and/or try to reproduce the issue. A repo with the issue or the output of the command above would help a lot if that's possible.

**Comment by GitFiend** [comment]
I've found a file status case that wasn't handled (T - type changed in index). The next release will include a fix for this, which will hopefully fix your issue. load_wip_patches will also return an error message instead of null in case this doesn't fix your problem.

**Comment by yama24** [comment]
oke thanks, i'll be waiting for the next version f this app.

**Comment by yama24** [comment]
the new version show me the error,, 
that's great! and i got the error

![image](https://github.com/GitFiend/Support/assets/33719224/f4d0721c-baf9-4c41-8550-024501dbc57a)

there is typechanged file from **symbolic link to regular file**.

the problem is not fixed yet but at least i know the problem and i know what have i do.

so thanks for your help. i realy appreciate it.

**Comment by yama24** [comment]
maybe the problem is another issue. so i close thus issue. Thanks

**Comment by GitFiend** [comment]
Thanks for the error message. I should be able to fix it with that.
