### ISSUE TITLE
[Feature Request] Missing graph

### ISSUE THREAD

**Issue by tbm98** [GitFiend/Support#37]
graph is important for tracking and manager process of project 
on gitlab web
![Screenshot-20191118220935-697x421](https://user-images.githubusercontent.com/52562340/69064073-299c6c00-0a50-11ea-85e8-4f04d2815efb.png)
in gitfiend tool
![Screenshot-20191118221018-562x304](https://user-images.githubusercontent.com/52562340/69064117-3e78ff80-0a50-11ea-927d-060ab20f40df.png)
:(

**Comment by GitFiend** [comment]
Hi tbm98,

What I like about having a graph is that it allows me to see what commits are on my branch, and see the ancestors of certain commits.

What I don't like about the graph is that in some repos it looks a bit like this:
![](https://memegenerator.net/img/images/71382958/crazy-charlie.jpg)

GitFiend shows arrows when you select a commit. I'm currently working on improving this and showing more information. Here's a quick preview:
![image](https://user-images.githubusercontent.com/47970508/69096425-4456fb00-0ab9-11ea-9f73-dbbd50c97ff4.png)
Note: I can't show the tooltips in a screenshot, and this is a work in progress.

**Comment by GitFiend** [comment]
This was improved in v0.21. I plan on adding more over time.

**Comment by tbm98** [comment]
@GitFiend Thank you about that!

**Comment by weiping-playnext** [comment]
How about leaving the "commit" view as it is and change the "branch" view to that of a graph?
The graph is very useful for me to track what commits have been merged into a master branch.
The current "commit" view is helpful if I know the commit beforehand and just tracking to see which branches have integrated it but it is not helpful vice-versa in tracking the history of a single branch to see what commits it contains.

**Comment by CieNTi** [comment]
I was looking for this question because I found it an amazing client which, for me, only lacks this feature. So +1 here!

As a suggestion on this subject, maybe is easier to implement as a previous "fast" step something like you do with the author color?

I don't know how easy or hard is for you to is to programmatically differentiate between commits already merged, and the ones that now (thinking in the case a branch does not die after a merge), but assuming is not hard, maybe picking a color for commits belonging a branch, then using same but darker colors for commits on the same branch already commited could do the job.

Thanks for this client!

**Comment by GitFiend** [comment]
@weiping-playnext Using the branches view is an interesting idea. I agree that it's hard to see what commits are on a branch you don't have checked out. I plan to improve this.

**Comment by GitFiend** [comment]
Thanks @CieNTi. If I understand your idea correctly, I've considered doing something like that when you hover over a branch. This gets around the problem that the same commit could be on 20 different branches.

**Comment by CieNTi** [comment]
Hi @GitFiend, thanks for your answer.

I was referring to assign a base color for a branch (you already do that if I'm not wrong), then colorize each line according to the branch it belongs to, darker if already merged at some point, lighter if not (or any other kind of "encoding").

But the main idea behind it, is to fastly and easily look and see that kind of information (like a picture-overview), instead of having to mouse over each line to see if it belongs to some branch or not.

Does this makes sense for you?

**Comment by GitFiend** [comment]
@CieNTi Oh, I think so. Do you want to make it easier to tell what commits are on your current branch? Currently, you can open a commit that's on your current branch and there will be a coloured dot beside every commit on that branch, but you want to make it easier than that?

**Comment by WieFel** [comment]
+1 on this.
I just tried GitFiend, coming from GitKraken. And I desperately miss a graph representation. It would help so much to easily see branches and distinguish commits. Would very much appreciate to have it in GitFiend! ;)

**Comment by CieNTi** [comment]
Hi @WieFel !
At the end I moved to VSCode + git graph, see: https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph

![image](https://user-images.githubusercontent.com/5205702/120240347-9f49e080-c260-11eb-8e34-73586703dafe.png)

I was using GitKraken since the last years, and I may miss the gitflow helper, but definitely it looks great, multiple color, branch and commit info ... I recommend you to test it

**Comment by WieFel** [comment]
@CieNTi thanks, I also had discovered that one.
However, I don't actually like it that much. Compared to GitKraken it is still a little un-handy. In GitKraken you see everything you need right away: graph, commits. And it is easy to navigate through changes in every commit.

I wonder why still no single open source git client for linux can manage to have a good integrated branch graph view, at one glance and side by side with commits...

This would really be a good oportunity for GitFiend to take the next step and differentiate itself from the rest!

**Comment by CieNTi** [comment]
I fully agree with you

**Comment by GitFiend** [comment]
This has now been added to GitFiend. Hope it helps!

**Comment by WieFel** [comment]
Thanks for letting me know! I wilk check it out and report back 😉
