### ISSUE TITLE
Nice build tool, Love it but any support for command line launching?

### ISSUE THREAD

**Issue by duqcyxwd** [GitFiend/Support#4]
Is there any way I can launch it though command line and it also accept a repo root path? 

Such as:
```
gitFiend ~/repos/newProject
```
It will open that project in gui.

**Comment by GitFiend** [comment]
Thanks duqcyxwd. That sounds like a good idea. I'll look into it.

**Comment by GitFiend** [comment]
In the next version you will be able to pass a repo path to GitFiend as an argument and it will load it.

On mac you will be able to do:
`open -a GitFiend --args ~/repos/newProject`

You could then use a shell script to simplify further, though in my testing this seemed confuse the Mac credential manager on private repos. I don't want to add a post setup script to do this because I want to keep security simple.

**Comment by vladimyr** [comment]
> On mac you will be able to do:
> `open -a GitFiend --args ~/repos/newProject`

@GitFiend Currently, in v0.22.8, this might fail due to #9 If you pass `.` as `--args` GitFiend assumes root path. A hacky workaround is to make sure path is absolute before passing it to GitFiend:
```sh
#!/bin/sh

git_dir=$(perl -e 'use Cwd "abs_path"; print abs_path(shift)' "$1")
open -a GitFiend --args "$git_dir"
```

**Comment by GitFiend** [comment]
Thanks @vladimyr. I've got a fix for the relative path issue coming in the next version.

**Comment by vladimyr** [comment]
> Thanks @vladimyr. I've got a fix for the relative path issue coming in the next version.

Great!

**Comment by vladimyr** [comment]
@GitFiend Just wanted to say that I've updated cask definition (https://github.com/Homebrew/homebrew-cask/pull/81491) and tested CLI invocation. It now works perfectly! 👍 💯

**Comment by GitFiend** [comment]
@vladimyr Excellent, thanks!
